### ISSUE TITLE
Error message on save rolling.

### ISSUE THREAD

**Issue by Corun-Kail** [bmos/FG-PFRPG-Malady-Tracker#1]
When clicking roll test button I receive error message in Fantasy Grounds Classic 3.3.11:

> Script Error: [string "scripts/manager_actions.lua"]:548: attempt to call field 'isClientFGU' (a nil value)

Disease Tracker: 1.2.0.
I have multiple other extensions installed, so might be some collission there, but error message suggests something different. As I have no experience with debugging in FGC, so if you require extra logs please inform me what data should I provide you with.

**Comment by bmos** [comment]
Try running it without the other extensions, a lot of extensions that haven't been updated to handle 3.3.11 properly will return that error (as this function is new in 3.3.11). Especially if you have Kelrugrem's save versus tags (or an extension that contains it).
