### ISSUE TITLE
Automatic (Timed) Rolls

### ISSUE THREAD

**Issue by Ma-Ko-dev** [bmos/FG-PFRPG-Malady-Tracker#19]
Hi,

i have installed Malady tracker, Maladies Library and the Clock Adjuster (all from forge) but it seems like i dont get the automatic rolling to work when there is an onset or frequenzy for example. There is no Button like in the preview Video for some reason even though i installed everything that i need. I set up a Calender and see the GUI for adding days, hours etc. too. So Clock Adjuster is definitively installed.

I am using the latest steam release of FG Unity and running a Pathfinder 1e Module.

I would appreciate some help with this :)

**Comment by bmos** [comment]
Sorry I'm just seeing this now!

This feature was removed a couple years ago as Clock Adjuster couldn't handle rounds. I made my own version of Clock Adjuster to implement that, but I never got it working right (it would roll extra saves or not enough) and abandoned that project.
